### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by pappjr** [rfsp/r#23]
After installing the app, when I go to 'Setup', enter the library location for R on my Splunk server (/usr/bin/R) and hit 'Save', there's an error and I'm directed to a screen with this message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
`<response>`
`<messages>`
`<msg type="ERROR">INTERNAL SERVER ERROR</msg>`
`</messages>`
`</response>`

at this URL https://splunk.mycompany.com:8000/dj/en-us/r/setup/

Continuing to investigate myself, but other users might be seeing something similar.

**Comment by rfsp** [comment]
I just uploaded a new version of the R Project Splunk app. It contains a fix with regards to the setup page.

Does this solve your problem?

**Comment by pappjr** [comment]
It did not fix the problem :-( - same error.

I even tried completely deleting the R Project Splunk app then reinstalling it.

Just a few notes - this is a distributed environment (2 SH's, 2 IDX's) all running Ubuntu. I installed the app on an SH, and tried using the setup page from multiple browsers with the same result.

I installed the app locally on my Windows 7 machine, and it gave me an error at first, but then when I retried it (after the error) it allowed me to save.

Good luck chasing this down - let me know if you need more info. I'm really excited to put this to use!

![image](https://cloud.githubusercontent.com/assets/9811487/9395920/35332a9e-4746-11e5-8eaa-193ac36f356a.png)

**Comment by rfsp** [comment]
Hmm, I'm surprised. Sure you updated to the latest on Splunkbase (apps.splunk.com)?

If so, may we do a Skype Screen Sharing or a WebEx session?

**Comment by pappjr** [comment]
Yes I'm positive, I used the r-project_0313.tgz download from splunkbase.

I actually manually updated the path in local.conf and was able to run R commands. I think there's just something wrong with the UI. I can show you on a WebEx sometime next week if you're available. I'm almost completely free during PST working hours next week

Have you tested in a distributed environment/on Linux machines?

![image](https://cloud.githubusercontent.com/assets/9811487/9417155/e44d0aaa-47fe-11e5-8bbb-83570441db12.png)

**Comment by rfsp** [comment]
Let's schedule the WebEx offline. May you send a message to rfujara@splunk.com?

Linux, yes I just tested the latest version in Ubuntu Desktop. But it's not a distributed environment.

**Comment by pappjr** [comment]
After reviewing the problem together we were able to resolve it. The problem was caused by a conflict with another app on the Splunk Search Head (Splunk_TA_box specifically). R Project app was updated to ensure it's necessary path would be unique and not conflict with other paths (i.e. 'framework')
